Repository likelion-lab15/essentia, pull requests merged in 2023-12, with the labels that each got.

#49 [#22][🎨Style] 로그인 페이지 스타일 완성
  src/app/globals.css
  src/app/signin/page.tsx
Labels: 💄스타일

#57 [#18][✨Feat] 회원가입 기능 완성
  src/app/signup/page.tsx
Labels: ✨기능, 🟥RED

#63 [#62][🎨Style] Header 공용 컴포넌트 레이아웃 스타일 완성
  public/blackheart-icon.svg
  public/heart-icon-black.png
  public/search-icon.png
  public/search-icon.svg
  public/signin-icon.png
  public/signin-icon.svg
  public/user-icon.png
  public/user-icon.svg
  src/components/Header.tsx
Labels: 💄스타일, 🗼마크업

#65 [#66][🎨Style] mypage/shoppinginfo 스타일 완성 및 mypage/userinfo 기본 스타일
  src/app/mypage/shoppinginfo/page.tsx
  src/app/mypage/userinfo/page.tsx
  src/containers/Filter.tsx
Labels: 💄스타일, 🗼마크업

#69 [#68][🎨Style] Input 공용 컴포넌트 레이아웃 스타일 완성
  src/components/Input.tsx
  src/components/_index.ts
Labels: 💄스타일, 🗼마크업

#71 [🎨Style] Button 공용 컴포넌트 제작, Input 공용 컴포넌트에 오류메세지 추가
  src/app/signup/page.tsx
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/_index.ts
Labels: 💄스타일, 🛠리팩토링, 🗼마크업

#78 [🛠Refactor] 마이페이지 라우터 재설계 및 컴포넌트 구조 변경
  src/app/mypage/history/_components/BuyHistoryTable.tsx
  src/app/mypage/history/_components/Membership.tsx
  src/app/mypage/history/_components/MoreButton.tsx
  src/app/mypage/history/_components/SellHistoryTable.tsx
  src/app/mypage/history/_components/_index.ts
  src/app/mypage/history/_functions/getHistoryData.ts
  src/app/mypage/history/buyhistory/page.tsx
  src/app/mypage/history/page.tsx
  src/app/mypage/history/sellhistory/page.tsx
  src/app/mypage/shoppinginfo/_components/BuyHistoryTable.tsx
  src/app/mypage/shoppinginfo/_components/SellHistoryTable.tsx
  src/app/mypage/shoppinginfo/page.tsx
  src/app/mypage/user/page.tsx
Labels: 🛠리팩토링

#80 [🛠Refactor] `MoreButton` 컴포넌트 `<Link>`로 수정
  src/app/mypage/edituser/page.tsx
  src/app/mypage/history/_components/MoreButton.tsx
  src/app/mypage/history/page.tsx
  src/components/FilterList.tsx
  src/constants/shoppingInfoList.ts
  src/constants/userInfoList.ts
Labels: 🔨기능수리

#85 [✨Feat] `refreshToken`으로 만료된 `accessToken` 업데이트
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/utils/_index.ts
  src/utils/fetchRefreshToken.ts
  src/utils/getRefreshToken.ts
Labels: ✨기능

#98 [✨Feat] 상품 상세 페이지의 네비게이션, 리뷰 기능 완성
  public/santal33.png
  src/app/productdetail/_sections/DetailImage.tsx
  src/app/productdetail/_sections/DetailNavigation.tsx
  src/app/productdetail/_sections/ProductInfo.tsx
  src/app/productdetail/_sections/RecommendedProductsSection.tsx
  src/app/productdetail/_sections/Review.tsx
  src/app/productdetail/_sections/_index.ts
  src/app/productdetail/page.tsx
  src/app/signup/page.tsx
Labels: ✨기능, 🛠리팩토링, 🟥RED

#106 [✨Feat] 상품 목록 페이지 필터 기능, 스크롤탑 버튼 완성
  public/scroll-top.svg
  src/app/admin/page.tsx
  src/app/products/_components/Products.tsx
  src/app/products/page.tsx
  src/app/sell/page.tsx
  src/components/FilterList.tsx
  src/components/ProductCard.tsx
  src/components/ScrollTopButton.tsx
  src/components/_index.ts
  src/constants/_index.ts
  src/constants/brandList.ts
Labels: ✨기능

#104 [🛠Refactor] 로그인 페이지 리팩토링 작업
  src/app/signin/_functions/_index.ts
  src/app/signin/_functions/postUserSignin.ts
  src/app/signin/page.tsx
  src/stores/useUserStore.ts
Labels: 🛠리팩토링

#108 [🚑119] Cannot find accesstoken 에러 해결
  src/api/axios.ts
  src/app/mypage/history/_functions/getHistoryData.ts
  src/components/Header.tsx
  src/hooks/_index.ts
  src/hooks/useTokens.ts
  src/stores/_index.ts
  src/stores/useUserStore.ts
  src/utils/_index.ts
  src/utils/fetchRefreshToken.ts
  src/utils/getAccessToken.ts
  src/utils/getRefreshToken.ts
Labels: 🚑119

#109 [🚑119] `FilterList`에 `onClick`이 추가됨으로 발생한 버그 해결
  src/components/FilterList.tsx
Labels: 🐛버그, 🚑119

#107 [✨feat] 상품 상세페이지 사이즈 옵션 기능, Header 수정
  public/ONYX-black.svg
  public/ONYX.svg
  public/ORH.svg
  public/blanche.webp
  src/app/productdetail/_sections/DetailNavigation.tsx
  src/app/productdetail/_sections/ProductInfo.tsx
  src/app/productdetail/page.tsx
  src/components/Header.tsx
  src/hooks/_index.ts
  src/hooks/useOutsideClick.ts
Labels: ✨기능, 🟥RED

#112 [🚑119] 500 Error 해결
  src/api/axios.ts
  src/app/globals.css
  src/app/mypage/edituser/page.tsx
  src/components/InputField.tsx
  src/components/_index.ts
Labels: 🚑119

#113 [🛠Refactor] 상품 상세페이지 네비게이션 리팩토링
  next.config.js
  src/app/product/_sections/ProductDetail.tsx
Labels: 🛠리팩토링

#114 [🛠Refactor] mainImages 백엔드 api 요구사항에 따라 수정
  src/app/admin/page.tsx
  src/app/sell/page.tsx
  src/components/FilterList.tsx
Labels: 💄스타일, 🔨기능수리, 🛠리팩토링, 🔰타입

#115 [🛠Refactor] 토큰 데이터 보관을 위한 `useTokenStore` 생성
  src/api/axios.ts
  src/app/signin/_functions/postUserSignin.ts
  src/app/signin/page.tsx
  src/components/Header.tsx
  src/hooks/useTokens.ts
  src/stores/_index.ts
  src/stores/useTokenStore.ts
Labels: 🔨기능수리

#117 [✨Feat] 회원정보 수정 기능 완성
  src/app/mypage/edituser/page.tsx
Labels: ✨기능

#119 [🎨Style] 상품 선택 페이지 마크업 & 스타일링 완성
  src/app/select/page.tsx
Labels: 🗼마크업

#120 [🐛Bug] `refreshToken` 반환 실패 버그 해결
  src/app/mypage/_components/UserName.tsx
  src/app/mypage/_components/_index.ts
  src/app/mypage/history/page.tsx
  src/app/mypage/layout.tsx
  src/components/Header.tsx
  src/hooks/useTokens.ts
Labels: 🐛버그

#126 [🛠Refactor] products/[_id] 라우터 설정
  src/app/page.tsx
  src/app/products/[_id]/_sections/ProductDetail.tsx
  src/app/products/[_id]/_sections/ProductInfo.tsx
  src/app/products/[_id]/_sections/_index.ts
  src/app/products/[_id]/buy/page.tsx
  src/app/products/[_id]/order/page.tsx
  src/app/products/[_id]/page.tsx
  src/app/products/[_id]/sell/page.tsx
  src/components/ProductCard.tsx
Labels: ✨기능, 🛠리팩토링

#129 [✨Feat] Header에서 로그인 상태를 체크하여 조건부 렌더링하도록 기능 추가
  public/signin-icon.svg
  public/signout-icon.svg
  src/components/Header.tsx
  src/constants/_index.ts
  src/constants/naviList.ts
Labels: ✨기능

#128 [✨Feat] 내 관심상품 페이지 완성
  public/heart_empty.svg
  public/heart_fill.svg
  src/app/mypage/wishlist/page.tsx
Labels: ✨기능, 💄스타일, 🗼마크업

#131 [🚑119] Cannot read property of 'null' 에러 해결
  src/api/axios.ts
Labels: 🐛버그, 🚑119

#135 [✨Feat] 주문 페이지 마크업 / 스타일링 및 기능 구현
  src/app/admin/page.tsx
  src/app/products/[_id]/order/page.tsx
  src/app/products/[_id]/sell/page.tsx
  tailwind.config.ts
Labels: ✨기능, 💄스타일, 🗼마크업

#138 [✨Feat] 상품 정렬 기능 구현
  src/app/products/_components/Products.tsx
Labels: ✨기능, 💄스타일, 🗼마크업

#136 [✨Feat] 리뷰 페이지, 리뷰 등록 기능 완성
  public/add_img.svg
  src/app/mypage/history/_components/BuyHistoryTable.tsx
  src/app/review/page.tsx
  src/stores/_index.ts
  src/stores/useReviewStore.ts
Labels: ✨기능, 💄스타일, 🗼마크업

#142 [✨Feat] products/[id] 하위 페이지들의 라우터 세팅
  src/app/products/[_id]/_sections/ProductDetail.tsx
  src/app/products/[_id]/_sections/ProductInfo.tsx
  src/app/products/[_id]/buy/page.tsx
  src/app/products/[_id]/page.tsx
  src/app/products/[_id]/sell/page.tsx
  src/components/ProductCard.tsx
Labels: ✨기능, 🛠리팩토링

#143 [🛠Refactor] 회원정보수정 페이지 타입 리팩토링
  src/app/mypage/edituser/page.tsx
  src/stores/useUserStore.ts
Labels: 🔰타입

#146 [🛠Refactor] useProductStore 를 이용하여 상품 데이터 관리하도록 변경
  src/app/products/[_id]/_sections/ProductInfo.tsx
  src/app/products/[_id]/buy/page.tsx
  src/app/products/[_id]/order/page.tsx
  src/app/signup/page.tsx
  src/components/ProductCard.tsx
  src/stores/_index.ts
  src/stores/useProductStore.ts
Labels: 🛠리팩토링

#150 [✨Feat] 상품 검색 기능 및 판매페이지 수정
  public/close-icon.svg
  public/search-big-icon.svg
  src/app/admin/page.tsx
  src/app/products/[_id]/sell/page.tsx
  src/components/Header.tsx
  src/components/ProductCard.tsx
  src/components/SearchBar.tsx
  src/components/_index.ts
Labels: ✨기능, 💄스타일

#154 [🛠Refactor] 회원가입, 상세페이지, 주문페이지 라우터 및 상태관리 리팩토링
  public/detailImage.png
  src/app/products/[_id]/_sections/ProductDetail.tsx
  src/app/products/[_id]/_sections/ProductInfo.tsx
  src/app/products/[_id]/order/page.tsx
  src/app/signup/page.tsx
  src/components/Header.tsx
  src/components/ProductCard.tsx
  tailwind.config.ts
Labels: ✨기능, 🛠리팩토링

#153 [✨Feat] 페이지네이션 기능 구현
  public/left-icon.png
  public/right-icon.png
  src/app/products/_components/Products.tsx
  tailwind.config.ts
Labels: ✨기능, 💄스타일, 🟥RED

#155 [✨Feat] 상품정보 수정페이지 완성
  src/api/axios.ts
  src/app/mypage/history/_functions/getHistoryData.ts
  src/app/mypage/history/page.tsx
  src/app/mypage/history/sellhistory/page.tsx
  src/app/products/[_id]/editsell/page.tsx
Labels: ✨기능

#158 [🛠Refactor] products[id] 라우터 내 컴포넌트 타입스크립트 리팩토링
  src/app/products/[_id]/_sections/ProductDetail.tsx
  src/app/products/[_id]/_sections/ProductInfo.tsx
  src/app/products/[_id]/buy/page.tsx
  src/app/products/[_id]/order/page.tsx
  src/app/products/[_id]/page.tsx
  src/app/signup/page.tsx
  src/components/InputField.tsx
  src/stores/useProductStore.ts
Labels: 🛠리팩토링

#159 [🛠Refactor] 타입스크립트 리팩토링 및 axios 환경변수 적용
  src/api/axios.ts
  src/app/admin/page.tsx
  src/app/products/[_id]/sell/page.tsx
  src/app/products/_components/Products.tsx
  src/app/products/page.tsx
  src/components/FilterList.tsx
  src/components/ProductCard.tsx
  src/components/SearchBar.tsx
Labels: 🛠리팩토링

#160 [✨Feat] 상품 상세페이지에 찜하기 통신 기능 추가
  src/app/products/[_id]/_sections/ProductInfo.tsx
Labels: ✨기능

#161 [🎨Style] 메인페이지 MagazineSection, BrandListSection 마크업 및 스타일링
  public/magazine-1.svg
  public/magazine-2.svg
  public/magazine-3.svg
  src/app/_sections/BrandListSection.tsx
  src/app/_sections/MagazineSection.tsx
  src/app/_sections/_index.ts
  src/app/page.tsx
  src/constants/brandList.ts
Labels: 💄스타일

#162 [🎨Style] Footer 마크업 및 스타일링
  public/Logo-ONYX.svg
  public/Logo.png
  public/facebook-icon.svg
  public/instagram-icon.svg
  public/twitter-icon.svg
  public/youtube-icon.svg
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/_index.ts
Labels: 💄스타일

#164 [⚙setting] 폰트 추가 및 tailwind 적용
  src/api/axios.ts
  src/app/_sections/BrandListSection.tsx
  src/app/_sections/PerfumeCarousel/PerfumeCarousel.tsx
  src/app/_sections/PerfumeCarousel/_components/PerfumeCarouselSwiper.tsx
  src/app/admin/page.tsx
  src/app/globals.css
  src/app/mypage/history/page.tsx
  src/app/mypage/history/sellhistory/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/wishlist/page.tsx
  src/app/products/[_id]/buy/page.tsx
  src/app/products/[_id]/editsell/page.tsx
  src/app/products/[_id]/order/page.tsx
  src/app/products/[_id]/sell/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/AddressModal.tsx
  src/components/FilterList.tsx
  src/components/Header.tsx
  src/containers/Filter.tsx
  src/hooks/useTokens.ts
  src/stores/useTokenStore.ts
  tailwind.config.ts
Labels: ⚙설정

#165 [🎨Style] 메인페이지 스타일 수정
  src/app/_sections/BrandListSection.tsx
  src/app/_sections/HeroSection.tsx
  src/app/_sections/MagazineSection.tsx
  src/app/page.tsx
Labels: 💄스타일

#168 [🛠Refactor] buy페이지에서 상품 목록 없을 때 마크업 추가, 헤더 라우터 수정
  src/app/products/[_id]/buy/page.tsx
  src/constants/naviList.ts
Labels: ✨기능, 🛠리팩토링

#169 [🔨refactor] 브랜드 필터 카테고리 api 사용
  public/products-right-icon.svg
  src/app/products/[_id]/sell/page.tsx
  src/app/products/_components/Products.tsx
  src/app/products/page.tsx
  src/components/ScrollTopButton.tsx
Labels: 🛠리팩토링
