Repository likelion-lab15/essentia, pull requests merged in 2023-11, with the labels that each got.

#26 [#22][🎨Style] 로그인 페이지 마크업
  src/app/login/page.tsx
  tailwind.config.ts
Labels: 🗼마크업

#32 [#30][🎨Style] 회원가입 페이지 마크업
  .gitignore
  src/app/signup/page.tsx
Labels: 🗼마크업

#29 [#21][✨Feat] 로그인 기능 완성
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signin/page.tsx
  src/stores/useUserStore.ts
  src/utils/_index.ts
  src/utils/cn.ts
Labels: ✨기능

#34 [#35][✨Feat] 상품목록 조회 기능 완성
  package-lock.json
  src/app/products/_components/Products.tsx
  src/app/products/_components/_index.ts
  src/app/products/page.tsx
  src/components/ProductCard.tsx
  src/components/_index.ts
Labels: ✨기능, 🗼마크업

#41 [#21][✨Feat] 회원가입 주소 검색 기능 추가
  .gitignore
  package-lock.json
  package.json
  src/app/signup/page.tsx
  src/components/AddressModal.tsx
  src/components/_index.ts
Labels: ✨기능

#43 [💯Review] 중간점검2
  .github/ISSUE_TEMPLATE/-✨기능--기능-템플릿.md
  .github/ISSUE_TEMPLATE/-🐛버그--버그-템플릿.md
  .github/ISSUE_TEMPLATE/-📜이슈--이슈-템플릿.md
  .gitignore
  package-lock.json
  package.json
  src/app/login/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/shoppinginfo/page.tsx
  src/app/mypage/userinfo/page.tsx
  src/app/page.tsx
  src/app/products/_components/Products.tsx
  src/app/products/_components/_index.ts
  src/app/products/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/AddressModal.tsx
  src/components/Filter.tsx
  src/components/ProductCard.tsx
  src/components/_index.ts
  src/stores/useUserStore.ts
  src/utils/_index.ts
  src/utils/cn.ts
Labels: 🔀병합
