Repository likelion-lab15/essentia, pull requests merged in 2024-02, with the labels that each got.

#204 [🛠Refactor] 상품 캐러셀 리팩토링 및 CSS 수정
  next.config.js
  package-lock.json
  package.json
  public/left-arrow-icon.svg
  public/right-arrow-icon.svg
  src/app/_sections/ExhibitionSection/ExhibitionSection.tsx
  src/app/_sections/ExhibitionSection/_components/Button.tsx
  src/app/_sections/ExhibitionSection/_components/_index.ts
  src/app/_sections/PerfumeCarousel/PerfumeCarousel.tsx
  src/app/_sections/PerfumeCarousel/_components/PerfumeCarouselSwiper.tsx
  src/app/_sections/_index.ts
  src/app/page.tsx
  src/app/products/[_id]/_sections/ProductDetail.tsx
  src/containers/CardCarousel/CardCarousel.tsx
  src/containers/CardCarousel/components/Bullets.tsx
  src/containers/CardCarousel/components/Buttons.tsx
  src/containers/CardCarousel/components/Card.tsx
  src/containers/CardCarousel/components/Slider.tsx
  src/containers/CardCarousel/components/_index.ts
  src/containers/_index.ts
Labels: 🛠리팩토링

#206 [🛠Refactor] 상품 페이지 컴포넌트 분리 및 react-query 설치
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/products/[_id]/_sections/ProductInfo copy.tsx
  src/app/products/[_id]/_sections/ProductInfo.tsx
  src/app/products/[_id]/_sections/_components/ButtonBox.tsx
  src/app/products/[_id]/_sections/_components/ReviewList.tsx
  src/app/products/[_id]/page.tsx
  src/app/tokens/userToken.ts
  src/components/RQProvider.tsx
  src/hooks/useModal.tsx
  tailwind.config.ts
Labels: ✨기능, 🛠리팩토링

#209 [🛠Refactor] Buy, Order 페이지를 서버 컴포넌트로 리팩토링
  src/app/products/[_id]/_sections/_components/ButtonBox.tsx
  src/app/products/[_id]/buy/_components/BackButton.tsx
  src/app/products/[_id]/buy/_components/BuyButton.tsx
  src/app/products/[_id]/buy/page.tsx
  src/app/products/[_id]/order/_components/OrderButton.tsx
  src/app/products/[_id]/order/page.tsx
Labels: 🛠리팩토링, 🚀성능

#210 [🛠Refactor] `NextAuth`를 도입한 유저 세션 기능 추가
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/components/Header.tsx
  src/contexts/NextAuthProvider/NextAuthProvider.tsx
  src/contexts/_index.ts
  src/middleware.ts
Labels: 🛠리팩토링

#212 [✨Feat] 브라우저에서 유저 세션에 접근할 수 있는 `useClientSession` 커스텀 훅 생성
  src/hooks/_index.ts
  src/hooks/useClientSession.ts
Labels: ✨기능

#213 [🛠Refactor] `UserName` 컴포넌트 서버 컴포넌트로 변환
  src/app/mypage/_components/UserName.tsx
Labels: 🛠리팩토링

#215 [🛠Refactor] `History` 페이지 컴포넌트 리팩토링
  src/app/mypage/history/_functions/getHistoryData.ts
  src/app/mypage/history/page.tsx
Labels: 🛠리팩토링

#214 [🛠Refactor] useReducer를 사용하여 판매 페이지 리팩토링
  src/api/axios.ts
  src/app/products/[_id]/sell/_components/SellForm.tsx
  src/app/products/[_id]/sell/_lib/fileUploader.ts
  src/app/products/[_id]/sell/page.tsx
  src/hooks/useSellFormReducer.ts
  types/formSellType.ts
Labels: ✨기능, 🛠리팩토링

#217 [🛠Refactor] `BuyHistoryTable` 컴포넌트 리팩토링
  src/app/mypage/history/_components/BuyHistoryTable.tsx
  src/app/mypage/history/_components/ReviewButton.tsx
  src/app/mypage/history/_components/SellHistoryTable.tsx
  src/app/mypage/history/_components/_index.ts
  src/app/mypage/history/_functions/_index.ts
  src/app/mypage/history/_functions/getRepliesData.ts
  src/app/mypage/history/page.tsx
Labels: 🛠리팩토링

#219 [🛠Refactor] 상품 페이지에서 위시리스트 관련 로직 리팩토링
  src/app/products/[_id]/_sections/ProductInfo copy.tsx
  src/app/products/[_id]/_sections/ProductInfo.tsx
  src/app/products/[_id]/_sections/_components/ButtonBox.tsx
Labels: 🛠리팩토링

#220 [🐛Bug] 로그아웃 상태일 때, 반환값 변경
  src/app/mypage/history/buyhistory/page.tsx
  src/app/mypage/history/sellhistory/page.tsx
  src/hooks/useClientSession.ts
  src/utils/getServerSession.ts
Labels: 🐛버그

#222 [🛠Refactor] 로그인하지 않은 유저가 위시리스트 버튼 누르면 알림뜨도록 추가
  src/app/products/[_id]/_sections/_components/ButtonBox.tsx
Labels: 🛠리팩토링

#223 [🛠Refactor] `WishList` 페이지 컴포넌트 리팩토링
  src/app/mypage/mywishlist/_components/EmptyMessage.tsx
  src/app/mypage/mywishlist/_components/WishCard.tsx
  src/app/mypage/mywishlist/_components/WishCardList.tsx
  src/app/mypage/mywishlist/_components/_index.ts
  src/app/mypage/mywishlist/_functions/_index.ts
  src/app/mypage/mywishlist/_functions/deleteWish.ts
  src/app/mypage/mywishlist/page.tsx
  src/app/mypage/wishlist/page.tsx
Labels: 🛠리팩토링

#224 [🛠Refactor] `MyWishList` 페이지 컴포넌트에 리액트 쿼리 도입
  public/loading-spinner.svg
  src/app/mypage/mywishlist/_components/Error.tsx
  src/app/mypage/mywishlist/_components/Loader.tsx
  src/app/mypage/mywishlist/_components/WishCard.tsx
  src/app/mypage/mywishlist/_components/WishCardList.tsx
  src/app/mypage/mywishlist/_components/_index.ts
  src/app/mypage/mywishlist/_functions/_index.ts
  src/app/mypage/mywishlist/_functions/getWishList.ts
  src/constants/shoppingInfoList.ts
Labels: 🛠리팩토링

#226 [🛠Refactor] ProductDetail.tsx를 서버 컴포넌트로 변경
  src/app/products/[_id]/_sections/ProductDetail-copy.tsx
  src/app/products/[_id]/_sections/ProductDetail.tsx
  src/app/products/[_id]/_sections/_components/ReviewList.tsx
  src/app/products/[_id]/_sections/_index.ts
  src/app/products/[_id]/page.tsx
Labels: 🛠리팩토링

#227 [🛠Refactor] 판매 페이지 리팩토링
  src/app/products/[_id]/sell/_components/SellForm.tsx
  src/app/products/[_id]/sell/page.tsx
  src/hooks/useSellFormReducer.ts
  types/formSellType.ts
Labels: 🛠리팩토링

#229 [🐛Bug] NextAuth 로그인 실패 에러 핸들링 로직 추가
  src/app/api/auth/[...nextauth]/route.ts
  src/components/Header.tsx
Labels: 🐛버그

#231 [✨feat] `fetch API`를 활용한 공용 함수 생성
  src/app/mypage/myreview/_lib/_index.ts
  src/app/mypage/myreview/_lib/getRepliesData.ts
  src/app/mypage/myreview/page.tsx
  src/fetch/fetch.ts
Labels: ✨기능

#232 [🛠Refactor] 상품 목록 페이지 서버 컴포넌트로 변환
  src/app/products/_components/Products copy.tsx
  src/app/products/_components/Products.tsx
  src/app/products/_lib/getSelectedBrand.ts
  src/app/products/page.tsx
  src/components/ProductCard.tsx
  src/constants/brandList.ts
Labels: 🛠리팩토링

#233 [🛠Refactor] `EditUser` 페이지 컴포넌트 리팩토링과 `useReducer`, `Server Action` 도입
  src/app/mypage/edituser/_actions/_index.ts
  src/app/mypage/edituser/_actions/action.ts
  src/app/mypage/edituser/_components/UserForm.tsx
  src/app/mypage/edituser/_components/_index.ts
  src/app/mypage/edituser/_reducers/_index.ts
  src/app/mypage/edituser/_reducers/reducer.ts
  src/app/mypage/edituser/page.tsx
  src/components/InputField.tsx
  src/fetch/fetch.ts
Labels: 🛠리팩토링

#234 [🛠Refactor] Header 스타일과 로그인 유무에 따라 조건부 동작하도록 변경
  public/ONYX.svg
  src/components/Header-copy.tsx
  src/components/Header.tsx
  src/components/Logo.tsx
  src/components/SignInToggleButton.tsx
  src/components/ToolTip.tsx
  src/components/_index.ts
Labels: ✨기능, 🛠리팩토링

#236 [🛠Refactor] Header의 로그인/로그아웃 컴포넌트를 서버 세션을 참조하도록 수정
  src/components/SignInToggleButton.tsx
Labels: 🛠리팩토링
